import { Project, Testimonial, PartnerLogo, ServiceItem, JournalArticle } from './types';

const ALL_PROJECTS: Project[] = [
  {
    id: 'brunelly',
    title: 'Brunelly',
    client: 'Pina Vida UK Limited',
    tagline: '',
    description: 'Owned end-to-end design for Brunelly (SaaS), evolving it from a Scrum tool into an AI-powered delivery platform with complex data-heavy interfaces, AI activity dashboards, sprint analytics, Kanban boards, and PR review workflows.',
    category: 'AI & SaaS',
    image: '/images/Frame 1.svg',
    images: [
      '/images/Frame 1.svg',
      '/images/Frame 2.svg',
      '/images/Frame 3.svg',
      '/images/Frame 4.svg',
      '/images/Frame 5.svg',
      '/images/Frame 6.svg',
    ],
    tags: ['AI SaaS', 'Sprint Analytics', 'Kanban Workflows', 'Design System'],
    year: 'Apr 2025 - Present',
    scope: ['AI Activity Dashboards', 'Sprint Analytics & Kanban', 'PR Review Workflows', 'Token Design System', 'HTML Code Specs', 'Clarity Heatmap Analysis'],
    metrics: 'Evolved legacy Scrum into an AI delivery engine with 3.4x faster PR review cycles',
    quote: {
      text: "Vinodh owned the end-to-end design evolution of Brunelly into an AI delivery platform. Replacing traditional Figma prototypes with development-ready HTML specs and building a versioned token system transformed our delivery velocity.",
      author: 'Product Leadership',
      role: 'Pina Vida UK Limited',
    },
    details: {
      overview: 'As UX Designer at Pina Vida UK Limited (Apr 2025 – Present), owned end-to-end design for Brunelly (SaaS), evolving the product from a traditional Scrum tool into a next-generation, AI-powered software delivery platform.',
      challenge: 'As Brunelly evolved beyond a traditional Scrum tool, the product needed to support increasingly complex workflows, data, and AI-powered capabilities without overwhelming the people using it.',
      solution: 'Designed complex data-heavy interfaces including AI activity dashboards, sprint analytics, customizable Kanban boards, and GitHub/GitLab PR review workflows. Utilized Microsoft Clarity session recordings and heatmaps to observe friction points and guide user-validated design decisions. Built a scalable token-based design system with versioned Foundations and Components, and experimented with interactive HTML prototypes as development-ready design specifications, effectively replacing static Figma prototypes while integrating Lovable, Replit, UX Pilot, Claude Code, and Claude Design directly into the workflow.',
      deliverables: [
        'AI Activity Dashboards & Real-Time Telemetry',
        'Sprint Analytics & High-Density Kanban Boards',
        'PR Review & Pull Request Automation Workflows',
        'Clarity Behavioral Heatmap & User Session Audits',
        'Scalable Token-Based Design System (Versioned Foundations & Components)',
        'Development-Ready Interactive HTML Design Specifications',
        'AI Toolchain Integration (Lovable, Replit, UX Pilot, Claude Code & Claude Design)',
      ],
      accentColor: '#7c3aed',
    },
  },
  {
    id: 'mindfulness-meditation-mvp',
    title: 'Mindfulness Meditation',
    client: 'Mindfulness Meditation',
    tagline: '',
    description: 'Mindfulness Meditation is a meditation and wellbeing service run by a monk based in the UK, offering meditation, counselling, mindfulness programs, retreats, webinars, and corporate wellbeing sessions.',
    category: 'Culture & DTC',
    image: '/images/frame 10.svg',
    images: [
      '/images/frame 10.svg',
      '/images/frame 11.svg',
      '/images/frame 12.svg',
      '/images/frame 13.svg',
      '/images/frame 14.svg',
    ],
    tags: ['MVP', 'UX/UI Design', 'Research', 'Prototyping', 'Testing', 'Handoff'],
    year: '2025',
    scope: ['MVP', 'UX/UI Design', 'Research', 'Prototyping', 'Testing', 'Handoff'],
    metrics: 'Transformed manual spreadsheets into a seamless digital booking experience',
    quote: {
      text: "Transforming our fragmented process into a centralized digital experience made it effortless for people to discover courses and book sessions.",
      author: 'Founding Monk',
      role: 'Mindfulness Meditation UK',
    },
    details: {
      overview: 'Mindfulness Meditation is a meditation and wellbeing service run by a monk based in the UK, offering meditation, counselling, mindfulness programs, retreats, webinars, and corporate wellbeing sessions.',
      challenge: 'Before the MVP, the entire booking process was managed manually through phone calls, conversations, and Excel spreadsheets. This created friction for both sides: booking required manual communication, tracing bookings was difficult, and managing spreadsheets was highly time-consuming for the stakeholder.',
      solution: 'Transform this fragmented process into a centralized digital experience where users can discover programs, purchase memberships, book sessions, manage bookings, and access mindfulness resources.',
      deliverables: ['Digital Booking Experience', 'Membership Management', 'Mindfulness Resource Library', 'Admin Operations Panel'],
      accentColor: '#15803d',
    },
  },
  {
    id: 'ceylo-tourism',
    title: 'Ceylo - Connecting Local Vendors with Tourists',
    client: 'Ceylo',
    tagline: '',
    description: "Connecting international tourists with local Sri Lankan vendors, artisans, and guides through an eco-friendly community platform promoting authentic, sustainable experiences.",
    category: 'Culture & DTC',
    image: '/images/Ceylo/Frame 40.svg',
    images: [
      '/images/Ceylo/Frame 40.svg',
      '/images/Ceylo/Frame 41.svg',
      '/images/Ceylo/Frame 42.svg',
      '/images/Ceylo/Frame 43.svg',
    ],
    tags: ['Sustainable Tourism', 'Community Platform', 'Marketplace', 'Mobile & Web UX'],
    year: '2024',
    scope: ['User Research', 'Marketplace Architecture', 'Vendor Onboarding', 'Design System'],
    metrics: 'Designed to bridge the authentic tourism gap and champion eco-friendly community vendor discovery',
    quote: {
      text: "Ceylo creates meaningful connections between travelers and grassroots artisans, making sustainable community tourism both effortless and impactful.",
      author: 'Founding Team',
      role: 'Ceylo Initiative',
    },
    details: {
      overview: "Sri Lanka's immense potential for community and sustainable tourism remains underutilized. Ceylo is a purpose-built platform that connects curious travelers directly with local vendors, authentic artisans, and eco-friendly hosts across the island.",
      challenge: "Tourists often miss authentic local experiences, while local vendors struggle with discoverability and digital reach. Existing travel platforms overlook eco-friendly practices and lack tools to support meaningful, community-first connections.",
      solution: "Designed a streamlined two-sided mobile and web platform with intuitive vendor discovery, verified sustainability badges, transparent localized pricing, and direct communication to foster genuine community impact.",
      deliverables: [
        'End-to-End Traveler Booking & Discovery Flow',
        'Frictionless Local Vendor Onboarding Suite',
        'Eco-Friendly Sustainability Metric System',
        'Bilingual Mobile-First Responsive Design System',
      ],
      accentColor: '#059669',
    },
  },
  {
    id: 'one-stop-marketplace',
    title: 'One stop marketplace - landing page',
    client: 'One Stop Marketplace',
    tagline: '',
    description: 'A one-stop marketplace landing page designed for seamless product discovery, vendor onboarding, and high-converting user journeys.',
    category: 'AI & SaaS',
    image: '/images/Frame 20.svg',
    images: [
      '/images/Frame 20.svg',
      '/images/Frame 21.svg',
    ],
    tags: ['Marketplace', 'Landing Page', 'UI/UX Design', 'Conversion'],
    year: '2024',
    scope: ['Landing Page Architecture', 'Marketplace UI', 'Conversion Optimization', 'Design System'],
    metrics: 'Engineered as a high-converting one-stop marketplace landing experience',
    details: {
      overview: 'A one-stop marketplace landing page connecting buyers and sellers with instant search, curated vendor discovery, and seamless transactions.',
      challenge: 'Multi-sided marketplaces often struggle with navigation complexity and cognitive overload on the entry landing page.',
      solution: 'Designed a unified, high-clarity landing interface with intuitive search filtering, featured categories, and clear value propositions that drive rapid conversion.',
      deliverables: ['Responsive Landing Page', 'Marketplace Discovery System', 'Interactive Prototypes', 'Component Design Specs'],
      accentColor: '#f59e0b',
    },
  },
  {
    id: 'pixelvault-crypto',
    title: 'PixelVault - Crypto dashboard',
    client: 'PixelVault',
    tagline: '',
    description: 'A comprehensive crypto dashboard built for tracking digital assets, on-chain portfolio analytics, real-time token metrics, and decentralized trading activity.',
    category: 'Fintech',
    image: '/images/Frame 30.svg',
    images: [
      '/images/Frame 30.svg',
    ],
    tags: ['Crypto Dashboard', 'Web3', 'Portfolio Analytics', 'UI/UX Design'],
    year: '2024',
    scope: ['Dashboard UI/UX', 'Portfolio Analytics Engine', 'Data Visualization', 'Design System'],
    metrics: 'Engineered for low-latency portfolio monitoring and real-time market data',
    details: {
      overview: 'PixelVault is an advanced crypto dashboard delivering institutional-grade portfolio intelligence, decentralized exchange activity tracking, and real-time token telemetry in one unified interface.',
      challenge: 'DeFi and crypto portfolio trackers often present dense, fragmented telemetry that overwhelms users across desktop and mobile views.',
      solution: 'Crafted a dark, high-contrast analytics dashboard with modular widget hierarchies, custom candlestick charting, and streamlined multi-wallet management.',
      deliverables: ['Responsive Web Dashboard', 'Real-time Charting System', 'Design Token Library', 'Mobile Companion Layouts'],
      accentColor: '#10b981',
    },
  },
  {
    id: 'ugc-website-redesign',
    title: 'UGC - Website Redesign',
    client: 'UGC',
    tagline: 'Modernizing creator-brand partnerships through high-converting digital storytelling.',
    description: 'A comprehensive website redesign for UGC, elevating creator-brand collaboration with seamless onboarding, modular campaign discovery, and refined editorial aesthetics.',
    category: 'Culture & DTC',
    image: '/images/UGC/Frame 50.svg',
    images: [
      '/images/UGC/Frame 50.svg',
    ],
    tags: ['Website Redesign', 'Creator Economy', 'UI/UX Design', 'Design System', 'Conversion'],
    year: '2025',
    scope: ['User Research', 'Information Architecture', 'Website Redesign', 'Design System', 'Responsive HTML Specs'],
    metrics: 'Engineered to accelerate creator onboarding and enhance brand campaign conversion',
    quote: {
      text: "The redesigned UGC website establishes an authoritative yet energetic presence, creating frictionless pathways for brand partnerships and creator applications.",
      author: 'Creative Leadership',
      role: 'UGC Platform',
    },
    details: {
      overview: 'UGC provides an intuitive platform bridging authentic digital creators with high-growth consumer brands. The website redesign elevates the digital experience to showcase campaign depth, clarify brand-creator value propositions, and drive inbound partnership momentum.',
      challenge: 'The previous website experienced ambiguous information architecture, where brand partnership queries and creator signups competed for focus, resulting in funnel friction and diminished conversion.',
      solution: 'Designed an elegant, modular digital storefront featuring dual-audience user flows, rich campaign showcase modules, crisp typography, and responsive component libraries built for high performance.',
      deliverables: [
        'Responsive High-Conversion Website Redesign',
        'Dual-Audience Navigation & Onboarding Funnels',
        'Modular Campaign Showcase & Media System',
        'Design System Tokens & Interactive Component Specs',
      ],
      accentColor: '#64748b',
    },
  },
  {
    id: 'wellnessgrocer-xr',
    title: 'WellnessGrocer - XR application',
    client: 'WellnessGrocer Systems',
    tagline: 'Immersive spatial wellness & grocery platform on visionOS.',
    description: 'An immersive, personalized wellness and grocery integration built for Apple Vision Pro, helping busy professionals manage their health, nutrition, and meal planning seamlessly.',
    category: 'Culture & DTC',
    image: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=1600&q=80',
    images: [
      'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=1600&q=80',
      'https://images.unsplash.com/photo-1556742049-0a67c5574f73?auto=format&fit=crop&w=1600&q=80',
    ],
    tags: ['spatial design', 'visionOS', 'ux research', 'xr interaction'],
    year: '2025',
    scope: ['Spatial Design', 'visionOS Layouts', 'UX Research', 'XR Interaction'],
    metrics: 'Engineered for immersive spatial interaction and automated meal planning',
    details: {
      overview: 'WellnessGrocer addresses the health management struggle of busy professionals aged 25-45 by integrating personalized grocery shopping with daily wellness experiences in an immersive visionOS interface.',
      challenge: 'Integrating mixed reality concepts cleanly with practical, high-frequency utility tasks such as cart management, calorie logging, and stress-tracking without visual clutter.',
      solution: 'An immersive, spatial 3D canvas built on Apple visionOS guidelines, featuring floating glassmorphic panels, intuitive gaze/gesture interactions, and unified health tracking panels.',
      deliverables: ['Spatial Interface Design', 'Interactive 3D Mockups', 'visionOS Layout Specifications', 'Personalization Engine'],
      accentColor: '#10b981',
    },
  },
  {
    id: 'mathru-app',
    title: 'Mathru - Pregnancy Care mobile App',
    client: 'Mathru Initiative',
    tagline: 'Supporting expectant Sri Lankan mothers with culturally tailored care.',
    description: 'A comprehensive, culturally tailored pregnancy tracking and support mobile application designed specifically to address the clinical and emotional needs of expectant mothers in Sri Lanka.',
    category: 'Culture & DTC',
    image: 'https://images.unsplash.com/photo-1518152006812-edab29b069ac?auto=format&fit=crop&w=1600&q=80',
    images: [
      'https://images.unsplash.com/photo-1518152006812-edab29b069ac?auto=format&fit=crop&w=1600&q=80',
      'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1600&q=80',
    ],
    tags: ['mobile app', 'maternal health', 'ux research', 'cultural customization'],
    year: '2025',
    scope: ['User Research', 'Maternal Health UX', 'Bilingual Support System', 'Mobile App Prototyping'],
    metrics: 'Culturally tailored pregnancy tracker supporting Tamil, Sinhala, and English',
    details: {
      overview: 'Mathru is Sri Lanka\'s first comprehensive, culturally-oriented pregnancy care application. It helps expectant mothers navigate their clinical journey with localized trackers, trimester guidelines, emergency tools, and secure medical storage.',
      challenge: 'Existing maternal health apps are tuned to Western medical guidelines and lack direct localized language support, cultural nutrition context, and integrations with Sri Lankan clinical schedules.',
      solution: 'Designed an intuitive, secure mobile interface offering dual-language (Sinhala & Tamil) FAQs, safe trimester forum modules, guided local prenatal routines, and offline-compatible instant-dial emergency controls.',
      deliverables: ['Maternal Care Tracking Core', 'Bilingual Content Directory', 'Calming Mindfulness System', 'Interactive High-Fidelity Prototypes'],
      accentColor: '#ec4899',
    },
  },
];

export const PROJECTS: Project[] = ALL_PROJECTS.filter(
  (p) => p.id !== 'wellnessgrocer-xr' && p.id !== 'mathru-app'
);

export const PARTNER_LOGOS: PartnerLogo[] = [
  { name: 'Google', src: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 32" fill="%2371717a"><text x="10" y="22" font-family="system-ui, -apple-system, sans-serif" font-weight="700" font-size="18" letter-spacing="-0.03em">Google</text></svg>' },
  { name: 'Virgin', src: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 32" fill="%2371717a"><text x="10" y="22" font-family="Georgia, serif" font-weight="bold" font-style="italic" font-size="20" letter-spacing="-0.02em">Virgin</text></svg>' },
  { name: 'Acquisition.com', src: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 140 32" fill="%2371717a"><rect x="10" y="8" width="14" height="14" rx="2" fill="%2371717a"/><text x="32" y="20" font-family="system-ui, -apple-system, sans-serif" font-weight="800" font-size="11" letter-spacing="0.15em">ACQUISITION</text></svg>' },
  { name: 'Healwell', src: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 32" fill="%2371717a"><circle cx="18" cy="16" r="8" stroke="%2371717a" stroke-width="2" fill="none"/><path d="M15 16h6M18 13v6" stroke="%2371717a" stroke-width="2"/><text x="34" y="20" font-family="system-ui, -apple-system, sans-serif" font-weight="700" font-size="14" letter-spacing="-0.01em">HEALWELL</text></svg>' },
  { name: 'Nolana', src: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 32" fill="%2371717a"><path d="M12 8c4 0 6 3 6 8s-2 8-6 8-6-3-6-8 2-8 6-8z" fill="none" stroke="%2371717a" stroke-width="2"/><text x="26" y="21" font-family="Georgia, serif" font-weight="600" font-size="15" letter-spacing="0.05em">Nolana</text></svg>' },
  { name: 'Aqua', src: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 32" fill="%2371717a"><path d="M10 22c0-4 4-9 6-11 2 2 6 7 6 11s-2.7 7-6 7-6-3-6-7z" fill="none" stroke="%2371717a" stroke-width="2"/><text x="30" y="21" font-family="system-ui, -apple-system, sans-serif" font-weight="600" font-size="16" letter-spacing="0.05em">AQUA</text></svg>' },
  { name: 'Gather', src: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 32" fill="%2371717a"><circle cx="10" cy="16" r="4" fill="%2371717a"/><circle cx="18" cy="12" r="3" fill="%2371717a"/><circle cx="18" cy="20" r="3" fill="%2371717a"/><text x="28" y="21" font-family="system-ui, -apple-system, sans-serif" font-weight="700" font-size="14" letter-spacing="0.02em">GATHER</text></svg>' },
  { name: 'FanMaker', src: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 32" fill="%2371717a"><path d="M8 12l8 8-4 4-8-8zm8 8l8-8 4 4-8 8z" fill="%2371717a"/><text x="32" y="21" font-family="system-ui, -apple-system, sans-serif" font-weight="800" font-size="13" letter-spacing="0.04em">FANMAKER</text></svg>' },
  { name: 'Parker', src: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 32" fill="%2371717a"><path d="M8 8h12v4H8zm0 8h12v4H8z" fill="%2371717a"/><text x="28" y="21" font-family="Georgia, serif" font-weight="bold" font-size="16" letter-spacing="0.05em">PARKER</text></svg>' },
  { name: 'Niamato', src: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 32" fill="%2371717a"><path d="M12 6l8 10-8 10-8-10z" fill="none" stroke="%2371717a" stroke-width="2"/><text x="28" y="21" font-family="system-ui, -apple-system, sans-serif" font-weight="700" font-size="14" letter-spacing="0.08em">NIAMATO</text></svg>' },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: 't-1',
    name: 'Raj Rajkumar',
    role: 'Charted Accountant',
    company: '',
    image: '/avatars/raj rajkumar.png',
    quote: "Vinodh’s hard work and dedication helped us to get our website up and running, and in a very short time frame too. We are completely thrilled with how it looks and how easily navigable it is. It has already brought a lot of interest from our members, and we are sure that is because of the informative & elegant design.",
    rating: 5,
  },
  {
    id: 't-2',
    name: 'Dilini Nanayakkara',
    role: 'UI / UX Engineer',
    company: '',
    image: '/avatars/dilini nanayakkara.png',
    quote: "Vinodh's clear communication bridges the gap between complex Design ideas and user needs. His ability to translate intricate concepts into actionable designs makes him a valuable asset to any project.",
    rating: 5,
  },
  {
    id: 't-3',
    name: 'Dulanjalee weerasinghe',
    role: 'Business analyst',
    company: '',
    image: '',
    quote: 'Vinodh effectively translates business requirements into clear, user-focused design solutions. His communication and collaboration make him a valuable part of the team.',
    rating: 5,
  },
];

export const SERVICES: ServiceItem[] = [
  {
    id: 's-1',
    number: '01',
    title: 'Brand Strategy and Identity',
    summary: 'Define positioning, market whitespace, tone of voice, and create an unmistakably memorable visual identity system that scales.',
    deliverables: [
      'Strategic Brand Positioning & Tone of Voice',
      'Primary Wordmark, Symbol & Responsive Lockups',
      'Custom Typography Pairings & Hierarchy Guidelines',
      'Dynamic Color Palettes & Contrast Rules',
      'Art Direction, Imagery & 3D Texture Rules',
      'Figma Identity Kit & Comprehensive Brand Book',
    ],
    duration: 'Week 1–2',
  },
  {
    id: 's-2',
    number: '02',
    title: 'Web Design and Development',
    summary: 'High-performance digital flagships engineered to convert visitors into believers. Custom animations, tactile micro-interactions, and zero bloat.',
    deliverables: [
      'UX Wireframing & Information Architecture',
      'High-Fidelity Desktop & Mobile UI in Figma',
      'Custom Motion & Interaction Prototypes',
      'Production-Ready Code (React, Next.js, Framer)',
      'Technical SEO, OG Meta, & Performance Optimization',
      'Scalable CMS Architecture & Content Workflows',
    ],
    duration: 'Week 2–3',
  },
  {
    id: 's-3',
    number: '03',
    title: 'Product UX/UI Design',
    summary: 'Translate brand essence into intuitive, delightful software interfaces that make sophisticated capabilities feel second nature.',
    deliverables: [
      'Core User Flow Architecture & Mapping',
      'Design Token Specification (Spacing, Radius, Elevation)',
      'Reusable Component Libraries (Shadcn/Tailwind aligned)',
      'Stateful Screens: Empty, Loading, Active, Error',
      'Interactive Micro-Animations & Sound Cues',
      'Developer Handoff Documentation & Specs',
    ],
    duration: 'Week 2–4',
  },
  {
    id: 's-4',
    number: '04',
    title: 'Motion Design and Content',
    summary: 'Breathe life into static systems with kinetic typography, 3D asset loops, product teaser films, and organic launch collateral.',
    deliverables: [
      'Brand Identity Reveal Animation',
      'Looping 3D & WebGL-Ready Video Assets',
      'Interactive SVG Icon Animations',
      'Launch Video Teaser (16:9 and 9:16 Social Cuts)',
      'Social Media Template Toolkit',
      'Lottie & CSS Animation Code Snippets',
    ],
    duration: 'Continuous / Sprint',
  },
];

export const JOURNAL_ARTICLES: JournalArticle[] = [
  {
    id: 'j-1',
    title: 'Why Most AI Companies Look Exactly the Same — And How to Escape It',
    category: 'Brand Strategy',
    readTime: '4 min read',
    image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
    excerpt: 'Dark mode with cyan glow and particle meshes has become the default visual crutch of tech. Here is how genuine differentiation starts with feeling.',
  },
  {
    id: 'j-2',
    title: 'The 14-Day Brand Sprint: Why Prolonged Agency Retainers Kill Momentum',
    category: 'Studio Process',
    readTime: '6 min read',
    image: 'https://images.unsplash.com/photo-1511556532299-8f662fc26c06?auto=format&fit=crop&w=800&q=80',
    excerpt: 'Founders do not need six months of committee decks. They need sharp conviction, clear angles, and production-ready identity files.',
  },
  {
    id: 'j-3',
    title: 'Typography as Sensory Texture: Choosing Glyphs That Speak Before Reading',
    category: 'Typography',
    readTime: '5 min read',
    image: 'https://images.unsplash.com/photo-1561070791-26c113006238?auto=format&fit=crop&w=800&q=80',
    excerpt: 'From Scandinavian slashed letterforms to Swiss neo-grotesque proportions, typography sets emotional temperature within 50 milliseconds.',
  },
  {
    id: 'j-4',
    title: 'Designing for the Autonomous Agent Era: What Changes for Interfaces',
    category: 'AI & UX',
    readTime: '7 min read',
    image: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?auto=format&fit=crop&w=800&q=80',
    excerpt: 'When agents start completing tasks on behalf of users, interfaces shift from operational dashboards to supervisory oversight.',
  },
];
